---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- Media:
    - Plex:
        icon: https://static-00.iconduck.com/assets.00/plex-new-icon-2048x2048-6fbtai37.png
        href: https://plex.tv.lan/
        description: Plex Media Server
        widget:
            type: plex
            url: http://192.168.0.5:32400
            key: uSD5Kodxr5zwX4Ws1FhV # see https://www.plexopedia.com/plex-media-server/general/plex-token/
    - Overseerr:
        icon: https://user-images.githubusercontent.com/1066576/125193232-b41d8900-e28e-11eb-801b-3b643f672536.png
        href: https://overseerr.branconet.lan/
        description: overseerr request system
        widget:
            type: overseerr
            url: http://192.168.0.5:5055
            key: MTY4OTg4NzM0NzQ3OTE1MjMwM2I3LTQyNDUtNDMzMC04MDM2LWQ1N2M1NGUwNTlhZQ==
    - Radarr:
        icon: https://static-00.iconduck.com/assets.00/radarr-icon-1845x2048-97le6lim.png
        href: https://radarr.branconet.lan/
        description: radarr movie scraper
        widget:
          type: radarr
          url: http://192.168.0.5:7878
          key: a1398a99742b4d5b9d47e2d491ddfecb
          enableQueue: true # optional, defaults to false
    - Sonarr:
        icon: https://res.cloudinary.com/razordarkamg/image/upload/v1621212884/SonarrV3_pufacd.png
        href: https://sonarr.branconet.lan/
        description: sonarr tv scraper
        widget:
          type: sonarr
          url: http://192.168.0.5:8989/
          key: 962f6aed45cd485a82a56327b21b57dc
          enableQueue: true # optional, defaults to false

    - Jackett:
        icon: https://user-images.githubusercontent.com/27040483/28728094-99f3e3f6-73c7-11e7-8f8d-28912dc6ac0d.png
        href: https://jackett.branconet.lan/
        description: jackett
        widget:
            type: jackett torrent scraper
            url: http://192.168.0.5:9117

    - qbittorrent:
        icon: https://icons.iconarchive.com/icons/papirus-team/papirus-apps/256/qbittorrent-icon.png
        href: https://qbittorrent.branconet.lan/
        description: qbittorrent p2p client
        widget:
            type: qbittorrent
            url: http://192.168.0.5:8112
            username: admin
            password: adminadmin

- Monitoring:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- CICD:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎

