---
services:      
    xteve:
      image: alturismo/xteve
      container_name: xteve
      hostname: xteve
      restart: unless-stopped
      networks:
        - container-swarm-network
      ports:
        - "34400:34400"
        - "1901:1900" #1900 used by Plex
      environment:
        TZ: ${TZ}
      volumes:
        - ${nfs_volumes_location}/xteve:/root/.xteve:rw
        - ${nfs_volumes_location}/xteve/config:/config:rw
        - /dev/shm:/tmp/xteve
    networks:
      container-swarm-network:
        external: true
