apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: http-echo
  namespace: flux-system
spec:
  interval: 5m
  releaseName: http-echo
  targetNamespace: http-echo
  storageNamespace: http-echo
  timeout: 8m
  chart:
    spec:
      chart: ./k8s-rewrite/charts/test-stack/http-echo
      sourceRef:
        kind: GitRepository
        name: migration-validated
        namespace: flux-system
      reconcileStrategy: Revision
      interval: 1m
  install:
    remediation:
      retries: 0
  upgrade:
    remediation:
      retries: 0
  values:
    enabled: false
    replicaCount: 0
