apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jtmb-dev
  namespace: flux-system
spec:
  interval: 5m
  releaseName: jtmb-dev
  targetNamespace: website-stack
  storageNamespace: website-stack
  timeout: 8m
  chart:
    spec:
      chart: ./k8s-rewrite/charts/web-app-stack/jtmb-dev
      sourceRef:
        kind: GitRepository
        name: migration-validated
        namespace: flux-system
      reconcileStrategy: Revision
      interval: 1m
  install:
    remediation:
      retries: 0
  upgrade:
    remediation:
      retries: 0
  values:
    enabled: true
    replicaCount: 1
    migration:
      staging: true
      routingReviewed: true
  suspend: false
