apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespaces.yaml
- bortus.yaml
- ets2.yaml
- gluetun.yaml
- mealie.yaml
- minecraft-exporter.yaml
- minecraft-website.yaml
- phpmyadmin.yaml
- pihole.yaml
- pihole-exporter.yaml
- ruckus-bot.yaml
- ruckus-db.yaml
- vaultwarden.yaml
- wordpress.yaml
- wordpress-db.yaml
- wordpress-redis.yaml
- xteve.yaml
- homepage.yaml
- bazarr.yaml
- flaresolverr.yaml
- jackett.yaml
- overseerr.yaml
- plex.yaml
- qbit-monitor.yaml
- qbittorrent.yaml
- radarr.yaml
- sonarr.yaml
- tautulli.yaml
- unpackerr.yaml
- ytdl.yaml
- http-echo.yaml
- whoami.yaml
- aplb.yaml
- jtmb-dev.yaml
- lucinda-art-gallery.yaml
- santos-web.yaml
