import prisma from "./db";
import fs from "fs/promises";
import path from "path";

const ANSIBLE_DIR = path.resolve(process.cwd(), "../ansible-playbook");
const VARS_FILE = path.join(ANSIBLE_DIR, "group_vars/all.yml");

// Template header for generated all.yml
const YAML_HEADER = `# Kubernetes Cluster Configuration Variables
# Auto-generated from Branconet K8s Manager DB
# Last synced: ${new Date().toISOString()}
# WARNING: Manual edits to this file will be overwritten on next deploy/sync.

---
`;

/**
 * Read all variables from the database and write them to group_vars/all.yml.
 * Variables are grouped by category, with category headers as comments.
 */
export async function syncVarsToYAML(): Promise<{ synced: number; file: string }> {
  const vars = await prisma.variable.findMany({
    orderBy: [{ category: "asc" }, { key: "asc" }],
  });

  // Group by category
  const groups = new Map<string, typeof vars>();
  for (const v of vars) {
    const cat = v.category || "general";
    if (!groups.has(cat)) groups.set(cat, []);
    groups.get(cat)!.push(v);
  }

  // Build YAML
  const lines: string[] = [YAML_HEADER];

  for (const [category, items] of groups) {
    lines.push(`# =============================================================================`);
    lines.push(`# ${category.toUpperCase()}`);
    lines.push(`# =============================================================================`);
    for (const item of items) {
      // Quote values that YAML would misinterpret (booleans, numbers, empty, IPs with slashes)
      const val = maybeQuote(item.value);
      lines.push(`${item.key}: ${val}`);
    }

/**
 * Add YAML quotes if value could be misinterpreted as a non-string type.
 */
function maybeQuote(value: string): string {
  if (value === "") return '""';
  // Already quoted
  if ((value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))) return value;
  // Booleans
  if (value === "true" || value === "false" || value === "yes" || value === "no") return `"${value}"`;
  // Numbers
  if (/^\d+(\.\d+)?$/.test(value)) return `"${value}"`;
  // Has special YAML chars that need quoting
  if (/[:{}\[\],&*?|>!%@`]/.test(value)) return `"${value}"`;
  return value;
}
    lines.push("");
  }

  const yamlContent = lines.join("\n") + "\n";

  // Ensure directory exists
  await fs.mkdir(path.dirname(VARS_FILE), { recursive: true });

  // Write file
  await fs.writeFile(VARS_FILE, yamlContent, "utf8");

  console.log(`[sync-vars] Synced ${vars.length} variables to ${VARS_FILE}`);

  return { synced: vars.length, file: VARS_FILE };
}

/**
 * Sync inventory from Node table to production.ini
 */
export async function syncInventoryToFile(): Promise<{ synced: number; file: string }> {
  const nodes = await prisma.node.findMany({
    where: { status: { not: "error" } },
  });

  const masters = nodes.filter((n) => n.role === "master");
  const workers = nodes.filter((n) => n.role === "worker");

  const lines: string[] = [
    "# Kubernetes Cluster Inventory",
    `# Auto-generated by Branconet K8s Manager`,
    `# Last synced: ${new Date().toISOString()}`,
    "",
    "[all]",
  ];

  for (const node of nodes) {
    lines.push(
      `${node.hostname} ansible_host=${node.ipAddress} ansible_user=brajam ansible_python_interpreter=/usr/bin/python3`
    );
  }

  if (masters.length > 0) {
    lines.push("");
    lines.push("[master]");
    masters.forEach((n) => lines.push(n.hostname));
  }

  if (workers.length > 0) {
    lines.push("");
    lines.push("[worker]");
    workers.forEach((n) => lines.push(n.hostname));
  }

  lines.push("");
  lines.push("[k8s_nodes]");
  nodes.forEach((n) => lines.push(n.hostname));

  // Read SSH key from DB, fall back to default
  let sshKey = "/home/brajam/.ssh/id_ed25519";
  try {
    const keyVar = await prisma.variable.findUnique({
      where: { key: "ansible_ssh_private_key_file" },
    });
    if (keyVar?.value) sshKey = keyVar.value;
  } catch { /* use default */ }

  lines.push("");
  lines.push("[all:vars]");
  lines.push("ansible_connection=ssh");
  lines.push(`ansible_ssh_private_key_file=${sshKey}`);
  lines.push("ansible_ssh_common_args='-o StrictHostKeyChecking=no'");

  const inventoryFile = path.join(ANSIBLE_DIR, "inventory/production.ini");
  await fs.mkdir(path.dirname(inventoryFile), { recursive: true });
  await fs.writeFile(inventoryFile, lines.join("\n") + "\n", "utf8");

  console.log(`[sync-inventory] Synced ${nodes.length} nodes to ${inventoryFile}`);

  return { synced: nodes.length, file: inventoryFile };
}
