FROM jenkins/jenkins:lts-jdk11

USER root
RUN apt update && \
    apt install ansible -y && \
    apt install git -y

COPY id_rsa /root/.ssh/id_rsa
COPY known_hosts /root/.ssh/known_hosts

RUN ssh-keyscan github.com >> /root/.ssh/known_hosts