version: '3.2'

services:
  agent:
    image: portainer/agent:2.18.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [ node.platform.os == linux ]

  portainer:
    image: portainer/portainer-ce:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    volumes:
      - ${container_volumes_location}/portainer:/data
    networks:
      - container-swarm-network
      - agent_network
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.portainer.rule=Host(`portainer.${domain_name}`)"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000" #uses internal docker port
        - "traefik.http.routers.portainer.entrypoints=websecure"
        - "traefik.http.routers.portainer.tls=true"
        - "traefik.http.routers.portainer.tls.certresolver=myresolver"
        - "traefik.http.routers.portainer.tls.domains[0].main=portainer.${domain_name}"
        # to add additional DNS names
        # - "traefik.http.routers.portainer.tls.domains[0].sans=portainer.${domain_name}"
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]

networks:
  agent_network:
    driver: overlay
    attachable: true
  container-swarm-network:
    external: true
