---
version: '3'
services:
  nextapp:
    image: nextcloud
    restart: always
    ports:
      - 8098:80
    volumes:
      - /home/ubuntu/container-program-files/next_cloud/data:/var/www/html
      - /home/ubuntu/container-program-files/plex_smb_share:/mnt/plex_smb_share:rw
    environment:
      PHP_UPLOAD_LIMIT: 16384
      NEXTCLOUD_TRUSTED_DOMAINS: ${master_node} ${worker_node_1} ${worker_node_2} nextcloud.branconet.lan
      NEXTCLOUD_ADMIN_USER: brajam
      NEXTCLOUD_ADMIN_PASSWORD: "${ADMIN_PASS}"
      OVERWRITEPROTOCOL: https
      NEXTCLOUD_UPDATE: 1
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextclouduser
      MYSQL_PASSWORD: "${ADMIN_PASS}"
      MYSQL_HOST: db
    networks:
      - container-swarm-network
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
        constraints: [node.role == manager]
  db:
    image: yobasystems/alpine-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "${ADMIN_PASS}"
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextclouduser
      MYSQL_PASSWORD: "${ADMIN_PASS}"
    expose:
      - "3306"
    networks:
      - container-swarm-network
    volumes: 
      - /home/ubuntu/container-program-files/next_cloud/mariadb:/var/lib/mysql
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
networks:
 container-swarm-network:
    external: true