version: '3.8'
services:
  home-assistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - '${container_volumes_location}/home-assistant/config:/config'
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
     - 8124:8123
    privileged: true
    deploy:
      mode: replicated
      replicas: 1
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-retries: "5"
        loki-batch-size: "400"
networks:
 container-swarm-network:
    external: true