version: '3.8'
services:
  home-assistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - '${container_volumes_location}/home-assistant/config:/config'
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - 8124:8123
    privileged: true
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ha.rule=Host(`ha.${domain_name}`)"
        - "traefik.http.services.ha.loadbalancer.server.port=8123" #uses internal docker port
        - "traefik.http.routers.ha.entrypoints=websecure"
        - "traefik.http.routers.ha.tls=true"
        - "traefik.http.routers.ha.tls.certresolver=myresolver"
        - "traefik.http.routers.ha.tls.domains[0].main=ha.${domain_name}"
        # to add additional DNS names
        # - "traefik.http.routers.ha.tls.domains[0].sans=ha.${domain_name}"
      mode: replicated
      replicas: 1
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-retries: "5"
        loki-batch-size: "400"
networks:
  container-swarm-network:
    external: true
