---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Cloud Developer Tooling:
    - Github:
        - abbr: GH
          icon: https://cdn-icons-png.flaticon.com/512/25/25231.png
          href: https://github.com/thechroniccoop/PRD-INFRA-thecroniccoop
    - AmazonEC2:
        - abbr: EC2
          icon: https://download.logo.wine/logo/Amazon_Elastic_Compute_Cloud/Amazon_Elastic_Compute_Cloud-Logo.wine.png
          href: https://us-east-1.console.aws.amazon.com/ec2/home?region=us-east-1#Instances:instanceState=running
    - Cloudflare:
        - abbr: CF
          icon: https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Cloudflare_Logo.png/480px-Cloudflare_Logo.png
          href: https://dash.cloudflare.com/2c1c72a2e0a6396e78a94ce47b53ee78/thechroniccoop.cc/dns/records
- LAN Developer Tooling:
    - VaultWarden:
        - abbr: VW
          icon: https://canada1.discourse-cdn.com/free1/uploads/vaultwarden/original/1X/26a1c808c7d5849039d47820eef7889b3415e5ec.png        
          href: https://vault.branconet.lan
    - Kanboard:
        - abbr: KB
          icon: https://yunohost.org/user/images/kanboard_logo.png       
          href: https://kanboard.branconet.lan
- Entertainment:
    - Reddit:
        - abbr: RE
          icon: https://seeklogo.com/images/R/reddit-logo-23F13F6A6A-seeklogo.com.png       
          href: https://old.reddit.com/
    - YouTube:
        - abbr: YT
          icon: https://upload.wikimedia.org/wikipedia/commons/e/ef/Youtube_logo.png        
          href: https://youtube.com/