apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- certificates.yaml
- legacy-routes.yaml
- ingress-service.yaml
- public-certificates.yaml
- backup-target.yaml
- ingress-deployment.yaml
