# for testing only
version: '3'

services:
  ez-backups:
    image: jtmb92/ez-backups:latest
    environment:
      scheduled_hour: '19'
      scheduled_minute: '16'
      WEBHOOK_URL: "${discord_webhook}"
      local_backup_method: tar
      source_dir: '${container_volumes_location}'
      backup_destination: /mnt/backups/server-backups
      TZ: America/New_York
    volumes:
      - ${container_volumes_location}:${container_volumes_location}
      - /mnt/backups/server-backups:/mnt/backups/server-backups
    deploy:
        replicas: 1
        placement:
            max_replicas_per_node: 1
    logging:
        driver: loki
        options:
            loki-url: "http://localhost:3100/loki/api/v1/push"
            loki-retries: "5"
            loki-batch-size: "400"
networks:
    container-swarm-network:
     external: true