version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    restart: always
    environment:
      SIGNUPS_ALLOWED: "true"
      PUID: 1000 
      PGID: 1000
      DATABASE_URL: mysql://bitwarden:${ADMIN_PASS}@mariadb:/bitwarden
    volumes:
      - ${container_volumes_location}/vault_warden/swarm:/data
    ports:
      - 8096:80
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 2
        # constraints:
        # - node.role==worker
  mariadb:
    image: yobasystems/alpine-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "${ADMIN_PASS}"
      MYSQL_DATABASE: bitwarden
      MYSQL_USER: bitwarden
      MYSQL_PASSWORD: "${ADMIN_PASS}"
    expose:
      - "3306"
    volumes: 
      - ${container_volumes_location}/vault_warden/mariadb:/var/lib/mysql
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        # constraints:
        # - node.role==worker