version: '3'
services:
  radarr:
    container_name: radarr
    restart: unless-stopped
    networks: 
     - container-swarm-network
    ports:
      - 7878:7878
    volumes:
      - ${container_volumes_location}/radarr:/config
      - /mnt/plex_smb_share:/media
      - /mnt/plex_smb_share:/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    image: linuxserver/radarr
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
        - node.hostname==master-node
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    networks: 
     - container-swarm-network
     - bridge
    environment:
      - LOG_LEVEL=info
      - TZ=America/LosAngeles
    volumes:
      - ${container_volumes_location}/overseerr/config:/config
    ports:
      - 5055:5055
    restart: unless-stopped
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
        - node.hostname==master-node

  sonarr:
    image: linuxserver/sonarr
    networks: 
     - container-swarm-network
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    volumes:
      - ${container_volumes_location}/sonarr/config:/config
      - /mnt/plex_smb_share:/media
      - /mnt/plex_smb_share:/downloads:/data
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/New_York
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
        - node.hostname==master-node
 
  jackett:
    container_name: jackett
    networks: 
     - container-swarm-network
    restart: unless-stopped
    ports:
      - 9117:9117
    volumes:
      - ${container_volumes_location}/jackett:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    image: linuxserver/jackett
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
        - node.hostname==master-node

    # restart: unless-stopped
    # deploy:
    #   replicas: 1
    #   placement:
    #     max_replicas_per_node: 1
    #     constraints:
    #     - node.hostname==master-node
networks:
 container-swarm-network:
    external: true
 bridge:
    external: true
    