version: '3'
services:
  radarr:
    container_name: radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    volumes:
      - /home/ubuntu/container-program-files/radarr:/config
      - /home/ubuntu/container-program-files/plex/movies:/movies
      - /home/ubuntu/container-program-files/deluge/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    image: linuxserver/radarr

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=info
      - TZ=America/LosAngeles
    volumes:
      - /home/ubuntu/container-program-files/overseerr/config:/config
    ports:
      - 5055:5055
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    volumes:
      - /home/ubuntu/container-program-files/sonarr/config:/config
      - /home/ubuntu/container-program-files/plex/tvseries:/tv
      - /home/ubuntu/container-program-files/deluge/downloads:/downloads
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/New_York
 
  jackett:
    container_name: jackett
    restart: unless-stopped
    ports:
      - 9117:9117
    volumes:
      - /home/ubuntu/container-program-files/jackett:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    image: linuxserver/jackett
  
  deluge:
    container_name: deluge
    restart: unless-stopped
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - UMASK_SET=000 
      - DELUGE_LOGLEVEL=error 
    volumes:
      - /home/ubuntu/container-program-files/deluge/config:/config
      - /home/ubuntu/container-program-files/deluge/downloads:/downloads
    image: linuxserver/deluge

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    ports:
     - 32400:32400
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=America/Toronto
      - ADVERTISE_IP=http://192.168.0.24:32400/
    volumes:
      - /home/ubuntu/container-program-files/plex/config:/config
      - /home/ubuntu/container-program-files/plex/tvseries:/tv
      - /home/ubuntu/container-program-files/plex/movies:/movies
    restart: unless-stopped
    