version: '3.8'
services:
  protonvpn:
    container_name: GlueTun-proton
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8112:8112 ##qbittorrent UI
      - 5800:5800 #tor
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=${protonvpn_user}
      - OPENVPN_PASSWORD=${protonvpn_pass}
      - VPN_TYPE=openvpn
      - PORT_FORWARD_ONLY=on
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
    volumes:
      - ${container_volumes_location}/gluetun:/tmp/gluetun
      - /mnt/plex_smb_share:/downloads:/downloads

  qbittorrent:
    container_name: qbittorrent
    network_mode: service:protonvpn
    depends_on:
      - protonvpn
      # - qbit-port-settings
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
      - WEBUI_PORT=8112
    env_file:
      - ${container_volumes_location}/gluetun/.env
    volumes:
      - ${container_volumes_location}/deluge/config:/config
      - /mnt/plex_smb_share:/downloads:/downloads
    image: lscr.io/linuxserver/qbittorrent:latest

  qbit-monitor:
    container_name: qbit-monitor
    depends_on:
      - qbittorrent
    image: docker.io/jtmb92/qbit-monitor
    environment:
      QBITTORRENT_HOST: "http://protonvpn:8112"
      QBITTORRENT_USERNAME: "brajam"
      QBITTORRENT_PASSWORD: "${ADMIN_PASS}"
      CHECK_INTERVAL_TORRENT_MONITORING: 10s
      CHECK_INTERVAL_FORWARDED_PORT: 1h
      PORT_FORWARD_FILE: /mnt/gluetun/forwarded_port
      DISCORD_WEBHOOK_URL: "${discord_webhook_media}" 
      PUID: "1000"
      PGID: "1000"
    volumes:
      -  ${container_volumes_location}/gluetun:/mnt/gluetun
      -  ${container_volumes_location}/qbit-monitor:/app/state

# networks:
#   container-swarm-network:
#     external: true
