FROM jenkins/jenkins:lts-jdk11

USER root
# Install Package Dependencies
RUN apt update && \
    apt install wget -y && apt install gpg -y && \
    apt install software-properties-common -y

# Add Hashicorp Repos for vault install
COPY install-vault.sh /tmp/install-vault.sh
RUN  bash /tmp/install-vault.sh

# Add Packages
RUN apt update && \
    apt install ansible -y && \
    apt install git -y && \
    apt install vault -y

# Add Jenkins plugins
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
RUN jenkins-plugin-cli --plugins \
 "git:5.2.0"\
 "github:1.37.2" \
 "mailer:463.vedf8358e006b_" \
 "ssh-credentials:308.ve4497b_ccd8f4" \
 "credentials:1271.v54b_1c2c6388a_" \
 "workflow-aggregator:596.v8c21c963d92d" \
 "discord-notifier:241.v448b_ccd0c0d6" \
 "publish-over-ssh:1.25" \
 "workflow-scm-step:415.v434365564324" \
 "ansicolor:1.0.3" 

# Remove Package Install Dependencies
RUN apt update && \
    apt remove wget -y && apt remove software-properties-common -y && \
    apt remove gpg -y
