version: "3.8"
services:
  jenkins:
    image: jtmb92/jenkins:brajam #jenkins/jenkins:lts-jdk11
    environment:
      TZ: 'America/Toronto'
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false -Dhudson.footerURL=https://jenkins.branconet.lan
      JENKINS_OPTS: --argumentsRealm.roles.user=admin --argumentsRealm.passwd.admin=${ADMIN_PASS}--argumentsRealm.roles.admin=admin
    restart: always
    cap_add:
      - IPC_LOCK
    networks:
     - container-swarm-network
    ports: 
      - "1337:8080"
      - "50000:50000"
    volumes:
      - '${container_volumes_location}/jenkins_home:/var/jenkins_home'
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
        - node.role==manager
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-retries: "5"
        loki-batch-size: "400"
networks:
 container-swarm-network:
    external: true