version: '3'
services:
  kanboard:
    image: kanboard/kanboard:latest
    ports:
      - "8099:80"
      - "9441:443"
    volumes:
      - ${container_volumes_location}/kaboard/kanboard_data:/var/www/app/data
      - ${container_volumes_location}/kaboard/kanboard_plugins:/var/www/app/plugins
