services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    networks:
      - container-swarm-network
    restart: unless-stopped
    volumes:
      - /home/ubuntu/container-program-files/prometheus:/etc/prometheus
      - /home/ubuntu/container-program-files/prometheus/prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - container-swarm-network
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: ${ADMIN_PASS}
    volumes:
      - /home/ubuntu/container-program-files/grafana/datasources:/etc/grafana/provisioning/datasources
    # deploy:
    #   mode: replicated
    #   replicas: 1
    #   placement:
    #     constraints:
    #     - node.hostname==raspberrypi
volumes:
  prom_data:
networks:
 container-swarm-network:
    external: true