# GitOps — Flux CD defaults
flux_git_url: ssh://git@github.com/jtmb/branconet-charts.git
flux_git_branch: validated
flux_git_path: ./flux/releases
flux_git_source_name: branconet-charts
flux_git_secret_name: branconet-charts-readonly
flx_namespace: flux-system
flx_version: "v2.9.6"
flx_components:
  - source-controller
  - kustomize-controller
  - helm-controller
  - notification-controller
