apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090 
    isDefault: true
    access: proxy
    editable: true

  - name: Loki
    type: loki
    url: http://loki:3100 
    access: proxy
    editable: true

  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: http://influx:8086
    jsonData:
      version: Flux
      organization: monitoring_stack
      defaultBucket: cadvisor
      tlsSkipVerify: true
    secureJsonData:
      token: 1234!12345!66781!