version: '3.8'
services:
  nordvpn:
    container_name: GlueTun-Nord
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8112:8112 ##qbit
      - 6881:6881 ##qbit
      - 6881:6881/udp #qbit
      - 5800:5800 #tor
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=${nord_user}
      - OPENVPN_PASSWORD=${nord_pass}
      - SERVER_REGIONS=Canada
      - VPN_TYPE=openvpn
  qbittorrent:
    container_name: qbittorrent
    network_mode: service:nordvpn
    depends_on:
      -  nordvpn
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8112
    volumes:
      - ${container_volumes_location}/deluge/config:/config
      - /mnt/plex_smb_share:/downloads:/downloads
    image: lscr.io/linuxserver/qbittorrent:latest
  tor:
    container_name: tor-browser
    network_mode: service:nordvpn
    depends_on:
      -  nordvpn
    restart: unless-stopped
    environment:
      - TZ=Etc/UTC
    image: domistyle/tor-browser
    volumes:
      - ${container_volumes_location}/plex/config:/config
      - /mnt/plex_smb_share/tv:/tv
      - /mnt/plex_smb_share/movies:/movies
      - /mnt/plex_smb_share/extras:/extras      
      - /dev/shm:/transcode
networks:
 container-swarm-network:
    external: true
    