version: '3.8'
services:
  nordvpn:
    container_name: GlueTun-Nord
    # networks:
    #   - container-swarm-network
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8112:8112 ##qbit
      - 6881:6881 ##qbit
      - 6881:6881/udp #qbit
      - 5800:5800 #tor
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - OPENVPN_USER=${nord_user}
      - OPENVPN_PASSWORD=${nord_pass}
      - SERVER_REGIONS=Canada
      - VPN_TYPE=openvpn
  qbittorrent:
    container_name: qbittorrent
    network_mode: service:nordvpn
    depends_on:
      - nordvpn
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
      - WEBUI_PORT=8112
    volumes:
      - ${container_volumes_location}/deluge/config:/config
      - /mnt/plex_smb_share:/downloads:/downloads
    image: lscr.io/linuxserver/qbittorrent:latest
# networks:
#   container-swarm-network:
#     external: true
