- name: Copy compose files from repo to the remote machine
  copy:
    src: "{{homedir}}/docker-compose/mini-linux/proxy-manager"
    dest: "/tmp/mini-linux"
  tags: [mini-linux]

- name: SET ADMIN PASS
  ansible.builtin.debug:
    msg: "{{ansible_sudo_pass}}"
  register: ADMIN_PASS
  no_log: true
  tags: [mini-linux]
  
- name: DEPLOY CONTAINERS TRAEFIK 
  vars:
    env_file: lan_domain_name={{lan_domain_name}} domain_name={{domain_name}} ADMIN_PASS={{ADMIN_PASS.msg}} mini_linux={{mini_linux}} master_node={{master_node}} worker_node_1={{worker_node_1}} worker_node_2={{worker_node_2}} nfs_volumes_location={{nfs_volumes_location}}
  shell: "{{env_file}} docker compose -f /tmp/mini-linux/proxy-manager/docker-compose.yml up -d"
  loop_control:
    label: "{{ item | regex_replace('^.*docker stack deploy', 'docker stack deploy') }}" #replaces env secrets from being shown in console output
  tags: [mini-linux]