version: '3.7'

services:
  traefik:
    image: traefik:v2.11
    deploy:
      mode: global
      # placement:
      #   constraints: [ node.hostname==masternode ]
      labels:
        - homepage.group=Proxy
        - homepage.name=traefik
        - homepage.icon=https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,c_fill,w_200,h_200/https://api.charmhub.io/api/v1/media/download/charm_9jjrT5C28rJhnK4yaGUEM51nQvWR26YG_icon_72c619c767b59b9147040735ad204012f1f37e79a190054bb64ca8c83c42e0c4.png
        - homepage.href=http://${master_node}:81/
        - homepage.description=Traefik Reverse Proxy and Load Balancer
    command:
      - --log.level=INFO
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.docker.swarmmode=true
      - --providers.docker.network=container-swarm-network
      - "--certificatesresolvers.myresolver.acme.email=james.branco@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesResolvers.myresolver.acme.httpChallenge=true"
      - "--certificatesResolvers.myresolver.acme.httpChallenge.entrypoint=web"
      - --api
      - --api.insecure=true
      - --api.dashboard=true
    ports:
      - target: 80
        published: 80
        mode: host
        protocol: tcp
      # Listen on port 443, default for HTTPS
      - target: 443
        published: 443
        mode: host
        protocol: tcp
      # additional ports
      - "81:8080" # Traefik dashboard, optional
    networks:
      - container-swarm-network
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${container_volumes_location}/letsencrypt:/letsencrypt"
  certbot:
    image: certbot/certbot
    deploy:
      placement:
        constraints: [ node.role==manager ]
      labels:
        - homepage.group=Proxy
        - homepage.name=certbot
        - homepage.icon=https://static-00.iconduck.com/assets.00/certbot-icon-2048x704-shevj0ph.png
        - homepage.description=letsencrypt certificate renewal
    volumes:
      - ${container_volumes_location}/certbot/conf:/etc/letsencrypt:/etc/letsencrypt
      - ${container_volumes_location}/certbot/www:/var/www/certbot
    # command: certonly --webroot -w /home/ubuntu/container-program-files/certbot/www --force-renewal --email thechroniccoop@gmail.com -d thechroniccoop.ca --agree-tos --dry-run
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - container-swarm-network
    restart: unless-stopped
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3001/loki/api/v1/push"
        loki-retries: "5"
        loki-batch-size: "400"
  whoami:
    image: traefik/whoami
    networks:
      - container-swarm-network
    deploy:
      labels:
        - homepage.group=Proxy
        - homepage.name=whoami
        - homepage.icon=https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,c_fill,w_200,h_200/https://api.charmhub.io/api/v1/media/download/charm_9jjrT5C28rJhnK4yaGUEM51nQvWR26YG_icon_72c619c767b59b9147040735ad204012f1f37e79a190054bb64ca8c83c42e0c4.png
        - homepage.href=http://${master_node}:2001/
        - homepage.description=Traefik whoami
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`whoami.${domain_name}`)"
        - "traefik.http.services.whoami.loadbalancer.server.port=2001" #uses internal docker port
        - "traefik.http.routers.whoami.entrypoints=websecure"
        - "traefik.http.routers.whoami.tls=true"
        - "traefik.http.routers.whoami.tls.certresolver=myresolver"
        - "traefik.http.routers.whoami.tls.domains[0].main=whoami.${domain_name}"
        # Add basic auth middleware
        - traefik.http.routers.whoami.middlewares=whoami-auth
        - traefik.http.middlewares.whoami-auth.basicauth.users=brajam:$$apr1$$0z21agij$$ue5mQ35aU.zi.X7J6dRWq.,shakiata:$$apr1$$ncze1lbu$$kDgBmbBEZK/BWely9tSh0/
    command:
      # It tells whoami to start listening on 2001 instead of 80
      - --port=2001
      - --name=iam
networks:
  container-swarm-network:
    external: true
