- name: Compress and backup containers
  tags: backup_all
  community.general.archive:
    path: /home/ubuntu/container-program-files/
    dest: /mnt/backups/server-backups/container-backups-{{ ansible_date_time.iso8601 }}.tgz

- name: Compress and backup mc-server
  tags: backup_mc
  community.general.archive:
    path: /home/ubuntu/container-program-files/mc-server
    dest: /mnt/backups/server-backups/mc-server-{{ ansible_date_time.iso8601 }}.tgz