- name: Create backup directory on local if it does not exist
  tags: backup_all
  ansible.builtin.file:
    path: '{{item}}'    
    state: directory
    mode: '0755'
  with_items:
   - /mnt/backups/server-backups/container-backups-{{ ansible_date_time.iso8601 }}

- name: Transfer files to backup drive
  become: true
  tags: backup_all
  copy:
    src: /home/ubuntu/container-program-files/
    dest: /mnt/backups/server-backups/container-backups-{{ ansible_date_time.iso8601 }}
    remote_src: yes


- name: Create mc backup directory on local if it does not exist
  tags: mc_backup
  ansible.builtin.file:
    path: '{{item}}'    
    state: directory
    mode: '0755'
  with_items:
   - /mnt/backups/server-backups/mc-server-{{ ansible_date_time.iso8601 }}

- name: Transfer MC files to backup drive
  tags: mc_backup
  copy:
    src: /home/ubuntu/container-program-files/
    dest: /mnt/backups/server-backups/mc-server-{{ ansible_date_time.iso8601 }}
    remote_src: yes
