  - name: Add new proxied A record
    uri:
      url: "https://api.cloudflare.com/client/v4/zones/{{ cf_zone_id }}/dns_records"
      method: POST
      body: '{"type":"A","name":"test.{{domain_name}}","content":"{{  PUB_IP }}","ttl":1,"proxied":true}'
      body_format: json
      headers:
        Authorization: "bearer {{ cf_key }}"
        Content-Type: "application/json"