- name: SET ADMIN PASS
  ansible.builtin.debug:
    msg: "{{ansible_sudo_pass}}"
  register: ADMIN_PASS
  no_log: true
  
- name: DEPLOY CONTAINERS STACK 
  vars:
    env_file: env cf_key={{cf_key}} email={{email}} cf_zone_id={{cf_zone_id}} discord_webook={{discord_webook}} domain_name={{domain_name}} ADMIN_PASS={{ADMIN_PASS.msg}} master_node={{master_node}} worker_node_1={{worker_node_1}} worker_node_2={{worker_node_2}} container_volumes_location={{container_volumes_location}}
  shell: "{{ item }}"
  with_items: "{{ stack_deploy }}"
  loop_control:
    label: "{{ item | regex_replace('^.*docker stack deploy', 'docker stack deploy') }}" #replaces env secrets from being shown in console output

- name: DEPLOY CICD CONTAINERS STACK
  tags: jenkins,vault
  vars:
    env_file: env cf_key={{cf_key}} email={{email}} cf_zone_id={{cf_zone_id}} discord_webook={{discord_webook}} domain_name={{domain_name}} ADMIN_PASS={{ADMIN_PASS.msg}} master_node={{master_node}} worker_node_1={{worker_node_1}} worker_node_2={{worker_node_2}} container_volumes_location={{container_volumes_location}}
  shell: "{{ item }}"  
  with_items: "{{ stack_deploy_cicd }}"
  loop_control:
    label: "{{ item | regex_replace('^.*docker stack deploy', 'docker stack deploy') }}" #replaces env secrets from being shown in console output
    
- name: SCALE SWARM CONTAINERS
  shell: "{{ item }}"
  with_items: "{{ swarm_scale }}"
