- name: create container dirs if they don't exist
  file:
    path: "{{ item }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: 0755
  with_items: "{{ container_paths }}"

- name: Copy a compose" files from repo to the remote machine to authenticate git repos on host machine
  copy:
    src: "/home/{{user_id}}/repos/{{repo_name}}/docker-compose"
    dest: "/tmp"
- name: Copy Grafana Configs
  copy: remote_src=False src=/home/{{user_id}}/repos/{{repo_name}}/docker-compose/monitoring-stack/grafana/datasource.yml dest=/home/ubuntu/container-program-files/grafana/datasources
- name: Copy Prometheus Configs
  copy: remote_src=False src=remote_src=True src=/home/{{user_id}}/repos/{{repo_name}}/docker-compose/monitoring-stack/prometheus/prometheus.yml dest=/home/ubuntu/container-program-files/prometheus

- name: SET ADMIN PASS
  ansible.builtin.debug:
    msg: "{{ansible_ssh_pass}}"
  register: ADMIN_PASS
  no_log: true

- name: DEPLOY CONTAINERS STACK 
  vars:
    env_file: env ADMIN_PASS={{ADMIN_PASS.msg}} master_node={{master_node}} worker_node_1={{worker_node_1}} worker_node_2={{worker_node_2}}
  shell: "{{ item }}"
  with_items: "{{ stack_deploy }}"
  loop_control:
    label: "{{ item | regex_replace('^.*docker stack deploy', 'docker stack deploy') }}" #replaces env secrets from being shown in console output

- name: SCALE SWARM CONTAINERS
  tags: 
    - smb
  shell: "{{ item }}"
  with_items: "{{ swarm_scale }}"
