- name: Create startup folder
  ansible.builtin.file:
    path: "/cron"
    state: directory

- name: Remove cron file scripts
  file:
    path: '{{item}}'
    state: absent
  with_items:
    - /cron/startup_job.sh
    - /cron/weekly_job.sh

- name: Create cron file sripts
  ansible.builtin.file:
    path: '{{item}}'
    state: touch
    mode: u+rw,g-wx,o-rwx
  with_items:
    - /cron/startup_job.sh
    - /cron/weekly_job.sh

- name: Make Scripts Executable
  file: dest={{item}} mode=a+x
  with_items:
    - /cron/startup_job.sh
    - /cron/weekly_job.sh

- name: Write Cron Job docker cleanup
  lineinfile: 
    dest: "/cron/weekly_job.sh"
    line: '{{ item }}'
  with_items:
    - 'docker system prune --all'

- name: Write Cron Job re-join NFS cluster after reboot
  lineinfile: 
    dest: "/cron/startup_job.sh"
    line: '{{ item }}'
  with_items:
    - 'sudo mount {{master_node}}:{{container_volumes_location}} {{container_volumes_location}}'

- name: Create Swarm Crontab entry for Weekly jobs
  ansible.builtin.cron:
    name: "Swarm job for docker image/volume cleanup"
    special_time: weekly
    job: "bash /cron/weekly_job.sh /cron/weekly_job.log 2>&1"

- name: Create Swarm Crontab entry for startup jobs
  ansible.builtin.cron:
    name: "Swarm job to rejoin nfs cluster on startup"
    special_time: "reboot"
    job: "bash /cron/startup_job.sh > /cron/startup_job.log 2>&1"