#ADD DNS ENTRIES FOR PIHOLE
- name: Clean DNS custom.list
  tags: dns
  delegate_to: master_node
  shell: rm -f /home/ubuntu/container-program-files/pihole/custom.list && touch /home/ubuntu/container-program-files/pihole/custom.list
- name: Add && enforce PiHole DNS Entries
  tags: dns
  lineinfile: 
    dest: "/home/ubuntu/container-program-files/pihole/custom.list"
    line: '{{ item }}'
  with_items:
    - '192.168.0.24 proxy.branconet.lan'
    - '192.168.0.24 pi.branconet.lan'
    - '192.168.0.24 vault.branconet.lan'
    - '192.168.0.24 budscraper.branconet.lan' 
    - '192.168.0.24 lucinda.branconet.lan' 
    - '192.168.0.24 santos.branconet.lan' 
    - '192.168.0.24 aplb.branconet.lan'
    - '192.168.0.24 converter.branconet.lan'
    - '192.168.0.25 true.nas.lan'
    - '192.168.0.19 worker.node2'
    - '192.168.0.16 worker.node1'
    - '192.168.0.24 swarm.master'
    - '192.168.0.24 grafana.branconet.lan'
    - '192.168.0.24 portainer.branconet.lan'
    - '192.168.0.24 plex.tv.lan'
    - '192.168.0.24 monitoring.branconet.lan'
    - '192.168.0.24 portainer.branconet.lan'
    - '192.168.0.24 deluge.branconet.lan'
    - '192.168.0.24 jenkins.branconet.lan'
    - '192.168.0.24 vpn.branconet.lan'
- name: Restart DNS service
  tags: dns
  shell: docker service update pi_pihole