#ADD DNS ENTRIES FOR PIHOLE
- name: Clean DNS custom.list
  tags: dns
  delegate_to: master_node
  shell: 'rm -f {{container_volumes_location}}/pihole/custom.list \ 
          && touch {{container_volumes_location}}/pihole/custom.list'
- name: Add && enforce PiHole DNS Entries
  tags: dns
  lineinfile: 
    dest: "{{container_volumes_location}}/pihole/custom.list"
    line: '{{ item }}'
  with_items:
    - '{{master_node}} proxy.branconet.lan'
    - '{{master_node}} pi.branconet.lan'
    - '{{master_node}} vault.branconet.lan'
    - '{{master_node}} budscraper.branconet.lan' 
    - '{{master_node}} lucinda.branconet.lan' 
    - '{{master_node}} santos.branconet.lan' 
    - '{{master_node}} aplb.branconet.lan'
    - '{{master_node}} converter.branconet.lan'
    - '192.168.0.25 true.nas.lan'
    - '{{worker_node_2}} worker.node2'
    - '{{worker_node_1}} worker.node1'
    - '{{master_node}} swarm.master'
    - '{{master_node}} grafana.branconet.lan'
    - '{{master_node}} portainer.branconet.lan'
    - '{{master_node}} plex.tv.lan'
    - '{{master_node}} monitoring.branconet.lan'
    - '{{master_node}} portainer.branconet.lan'
    - '{{master_node}} qbittorrent.branconet.lan'
    - '{{master_node}} sonarr.branconet.lan'
    - '{{master_node}} radarr.branconet.lan'
    - '{{master_node}} overseerr.branconet.lan'
    - '{{master_node}} jenkins.branconet.lan'
    - '{{master_node}} vpn.branconet.lan'
    - '{{master_node}} nextcloud.branconet.lan'
    - '{{master_node}} uptime.branconet.lan'
    - '{{master_node}} mc.branconet.lan'
    - '{{master_node}} mc.branconet.lan'
    - '{{master_node}} vault.cicd.branconet.lan'
    - '{{master_node}} prom.branconet.lan'
    - '{{master_node}} tor.branconet.lan'
- name: Restart DNS service
  tags: dns
  shell: docker service update pi_pihole --force
  ignore_errors: true