- name: Add entries to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item.ip }}  {{ item.hostname }}"
    state: present
    create: yes
    validate: 'cat %s'
  loop:
    - { ip: "{{master_node}}", hostname: "masternode" }
    - { ip: "{{worker_node_1}}", hostname: "workernode1" }
    - { ip: "{{worker_node_2}}", hostname: "workernode2" }
  tags: glusterfs

- name: Add the GlusterFS repository
  apt_repository:
    repo: ppa:gluster/glusterfs-10
  tags: c

- name: Update the repositories
  apt:
    update_cache: yes
  tags: glusterfs

- name: Install GlusterFS
  apt:
    name: glusterfs-server
    state: present
  tags: glusterfs

- name: Start the GlusterFS service
  service:
    name: glusterd
    state: started
  tags: glusterfs

- name: Enable the GlusterFS service
  service:
    name: glusterd
    enabled: yes
  tags: glusterfs

- name: Create /gluster/volumes directory
  file:
    path: /gluster/volumes
    state: directory
    mode: '0755'
  tags: glusterfs

- name: Append line to /etc/fstab
  lineinfile:
    path: /etc/fstab
    line: 'localhost:/staging-gfs /mnt glusterfs defaults,_netdev,backupvolfile-server=localhost 0 0'
    create: yes
  tags: glusterfs

- name: Mount GlusterFS volume
  command: mount.glusterfs localhost:/staging-gfs /mnt
  tags: glusterfs

- name: Set ownership of /mnt to root:docker
  file:
    path: /mnt
    state: directory
    owner: root
    group: docker
    recurse: yes
  tags: glusterfs
