- name: Copy Jenkins dockerfile to mnachines
  tags: jenkins
  copy:
    src: "{{homedir}}/swarm/docker-compose/{{item}}"
    dest: "/tmp/dockerfiles"
  with_items:
   - jenkins-cicd

- name: Log into DockerHub
  docker_login:
    username: james.branco@gmail.com
    password: "{{ansible_sudo_pass}}"

- name: Build Jenkins Custom Image
  community.docker.docker_image:
    build:
      path: /tmp/dockerfiles/jenkins-cicd/dockerfile_
      nocache: true
    repository: jtmb92/jenkins
    name: jenkins:brajam
    source: build
    push: true
    force_tag: true

- name: Download Dockerfiles from repos
  ansible.builtin.git:
    repo: https://github.com/jtmb/cloudflare-ip-checker.git
    dest: '/tmp/dockerfiles/cloudflare-ip-checker'
    version: master

- name: Build cloudflare_ip_checker Image
  community.docker.docker_image:
    build:
      path: /tmp/dockerfiles/cloudflare-ip-checker/
      nocache: true
    repository: jtmb92/cloudflare_ip_checker
    name: cloudflare_ip_checker:latest
    source: build
    push: true
    force_tag: true