- name: Copy a "Jenkins Setup" file from repo to the remote machine to authenticate git repos on host machine

  copy:
    src: "/home/{{user_id}}/repos/{{repo_name}}/docker-compose/jenkins"
    dest: "/tmp"

- name: Copy a "id_rsa" file from repo to the remote machine to authenticate git repos on host machine
  copy:
    src: "/home/{{user_id}}/.ssh/id_rsa"
    dest: "/tmp/jenkins/id_rsa"

- name: Docker compose UP jenkins-server
  shell: |
    docker compose --env-file "/tmp/jenkins/.env" -p "jenkins-server" -f "/tmp/jenkins/docker-compose.yml" up -d --build

- name: Pause for 30 seconds to build app cache
  ansible.builtin.pause:
    seconds: 30

- name: "Save Jenkins password to var"
  shell: "cat /home/ubuntu/container-program-files/jenkins_home/secrets/initialAdminPassword"
  register: jenkins_secret
  ignore_errors: true
  failed_when: '"this task will not fail!" in jenkins_secret.stderr'

- name: Set a variable
  ansible.builtin.set_fact:
    myvar: "{{ jenkins_secret.stdout | to_json }}"
  ignore_errors: true

- name: Show Jenkins Secret
  debug:
    var: jenkins_secret.stdout
  ignore_errors: true

- name: Create a jenkins_home .ssh directory if it does not exist and set right permissios
  ansible.builtin.file:
    path: /home/ubuntu/container-program-files/jenkins_home/.ssh"
    state: directory
    mode: '400'

# - name: Auth jenkins with Github RSA
#   shell: |
#     docker exec jenkins-server-jenkins-1 chmod 400 /root/.ssh/id_rsa && ssh -T git@github.com
#   register: command_result
#   failed_when: '"Hi jtmb!" not in command_result.stderr'

- name: Copy a "id_rsa" file from repo to the remote machine to authenticate git repos on host machine
  copy:
    src: "/home/{{user_id}}/.ssh/id_rsa"
    dest: /home/ubuntu/container-program-files/jenkins_home/.ssh/id_rsa"