#ADD DNS ENTRIES FOR PIHOLE
- name: Clean DNS custom.list
  shell: rm -f /home/ubuntu/container-program-files/pihole/custom.list && touch /home/ubuntu/container-program-files/pihole/custom.list
- name: Add && enforce PiHole DNS Entries
  lineinfile: 
    dest: "/home/ubuntu/container-program-files/pihole/custom.list"
    line: '{{ item }}'
  with_items:
    - '192.168.0.24 proxy.branconet.lan'
    - '192.168.0.24 pi.branconet.lan'
    - '192.168.0.24 vault.branconet.lan'
    - '192.168.0.24 budscraper.branconet.lan' 
    - '192.168.0.24 lucinda.branconet.lan' 
    - '192.168.0.24 santos.branconet.lan' 
    - '192.168.0.24 aplb.branconet.lan'
    - '192.168.0.24 converter.branconet.lan'
    - '192.168.0.25 true.nas.lan'
    - '192.168.0.19 worker.node1'
    - '192.168.0.24 swarm.master'
- name: Restart DNS service
  shell: docker service update pi_pihole
