- name: Reboot the host
  reboot:
    reboot_timeout: 600  # Timeout for the reboot to complete
  tags: reboot 

- name: Wait for the host to come back online
  wait_for_connection:
    timeout: 300  # Timeout for the host to become available again
  tags: reboot 

- name: Verify the host is online and running
  command: uptime
  register: result
  tags: reboot 

- name: Show uptime
  debug:
    var: result.stdout
  tags: reboot 