- name: Reboot Hosts
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 30
    reboot_timeout: 3600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime

- name: Execute PI Cluster rejoin fix
  when: ansible_architecture == "armv7l"
  shell: "{{item}}"
  with_items:
    - 'sudo systemctl restart docker'
    - 'sudo mount {{master_node}}:{{container_volumes_location}} {{container_volumes_location}}'
    - 'docker ps'
