- name: "Set SSH Enviorment to alternate port"
  shell: "ufw allow ssh && \
            ufw allow 2002/tcp"

- name: Creates SSH hidden directory
  file:
      path: "{{homedir}}/.ssh"
      state: directory

- name: Regex replace ssh port
  replace:
    path: "/etc/ssh/sshd_config"
    regexp: '#Port 22'
    replace: "Port 2002"

- name: Regex replace pubkey auth
  replace:
    path: "/etc/ssh/sshd_config"
    regexp: '#PubkeyAuthentication yes'
    replace: "PubkeyAuthentication yes"

- name: Regex replace pass auth
  replace:
    path: "/etc/ssh/sshd_config"
    regexp: '#PasswordAuthentication yes'
    replace: "PasswordAuthentication no"
    
- name: Regex replace ChallengeResponseAuthentication
  replace:
    path: "/etc/ssh/sshd_config"
    regexp: 'ChallengeResponseAuthentication yes'
    replace: "ChallengeResponseAuthentication no"

- name: "Restart SSH Service"
  shell: "systemctl restart sshd"

- name: "Remove and dissable GUI in Ubuntu"
  shell: "apt-get purge ubuntu-desktop -y && \
            systemctl set-default multi-user"
  ignore_errors: true
  no_log: true