- name: Init a new swarm with default parameters #docker swarm init
  community.docker.docker_swarm:
    state: present

- name: Swarm Get Join Key
  become: true
  become_user: root
  shell: docker swarm join-token manager --quiet
  register: CLUSTER_JOIN_KEY

# - name: ADD nfs-kernel-server
#   become: yes
#   become_user: root
#   apt:
#     name: 
#       - nfs-kernel-server
#     update_cache: yes

# - name: Create share directory if it does not exist and set right permissios
#   ansible.builtin.file:
#     path: "{{nfs_volumes_location}}"
#     state: directory
#     mode: 0777
#     owner: nobody
#     group: nogroup

# - name: Ensure no NFS binds present
#   become: true
#   become_user: root
#   shell: |
#     systemctl stop nfs-server
#     umount -f -l {{nfs_volumes_location}}
#     systemctl start nfs-server 

# - name: Export Key for NTFS
#   become: true
#   become_user: root
#   lineinfile: 
#     dest: "/etc/exports"
#     line: '{{ item }}'
#   with_items:
#     - '{{nfs_volumes_location}} *(no_root_squash,rw,sync,no_subtree_check)'

- name: Create an external container-swarm-network
  become: true
  become_user: root
  docker_network:
    name: 'container-swarm-network'  
    scope: swarm
    state: present
    driver: overlay

- name: Create an external db-network
  become: true
  become_user: root
  docker_network:
    name: 'db-network'    
    scope: swarm
    state: present
    driver: overlay

# - name: Restart NFS server
#   become: true
#   become_user: root
#   shell: systemctl restart nfs-server