- name: Init a new swarm with default parameters #docker swarm init
  community.docker.docker_swarm:
    state: present

- name: Swarm Get Join Key
  become: true
  become_user: root
  shell: docker swarm join-token manager --quiet
  register: CLUSTER_JOIN_KEY

- name: Create share directory if it does not exist and set right permissios
  ansible.builtin.file:
    path: "{{container_volumes_location}}"
    state: directory
    mode: 0777
    owner: nobody
    group: nogroup

- name: Create an external container-swarm-network
  become: true
  become_user: root
  docker_network:
    name: 'container-swarm-network'  
    scope: swarm
    state: present
    driver: overlay

- name: Create an external db-network
  become: true
  become_user: root
  docker_network:
    name: 'db-network'    
    scope: swarm
    state: present
    driver: overlay
    