- name: Join Nodes to Cluster # docker swarm join --token {{ hostvars['master_node'].CLUSTER_JOIN_KEY.stdout }} {{master_node}}:2377
  docker_swarm:
    state: join
    join_token: "{{ hostvars['master_node'].CLUSTER_JOIN_KEY.stdout }}"
    remote_addrs: [ '{{master_node}}:2377' ]
  
- name: Create share directory if it does not exist and set right permissios
  ansible.builtin.file:
    path: "/home/ubuntu/container-program-files/"
    state: directory
    mode: 0777
    owner: nobody
    group: nogroup 

- name: Mount NTFS on clients
  become: true
  become_user: root
  shell: mount {{master_node}}:/home/ubuntu/container-program-files /home/ubuntu/container-program-files

