version: '3'

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 32402:32400
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=latest
      - TZ=America/Toronto
      - PLEX_CLAIM=claim-Tx_KpdAfeHSQoeRvLduc #claim token at https://www.plex.tv/claim/ (used for when a password change is needed or server needs to be reclaimed)
      - ADVERTISE_IP=http://${worker_node_2}:32402/
    volumes:
      - /var/plex-stack/plex2/config:/config
      - /mnt/plex_smb_share/tv:/tv
      - /mnt/plex_smb_share/movies:/movies
      - /mnt/plex_smb_share/extras:/extras
      - /dev/shm:/transcode
