# Plex Media PersistentVolumeClaims (Samba shares)
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-tv-pvc
  namespace: plex
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: smb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-movies-pvc
  namespace: plex
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: smb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvr-pvc
  namespace: plex
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: smb
