# PRE-provisioning VM
- name: "Provision Enviorment"
  strategy: linear
  hosts: all
  become: true 
  tasks:
  
  - name: Collect Server IP
    debug:
      msg: "{{ ansible_ssh_host }}"
  - name: Collect Server ARCH
    debug: 
       msg: '{{ansible_architecture}}'
  - name: Install Required Packages
    include: tasks/provisioning.yml
    tags: packages
  - name: Setup SSH
    include: tasks/ssh_setup.yml
    tags: ssh
  - name: Setup firewall
    include: tasks/ufw.yml
    tags: ufw

# Swarm setup
- name: "Configure Swarm"
  hosts: master_node
  become_user: "root"
  become: true
  tasks:
  - name: Install swarm
    include: tasks/swarm_master.yml
    tags: swarm

- name: "Join Swarm"
  hosts: 
    - worker_node_1
    - worker_node_2
  become_user: "root"
  become: true
  tasks:
  - name: Install swarm
    include: tasks/swarm_worker_join.yml
    tags: swarm

# Containers
- name: "Launch Swarm Containers"
  hosts: master_node
  become_user: "root"
  become: true
  vars_files:
    - vars/lists.yml
  tasks:
  - name: Git Clone App Repos
    include: tasks/clone_app_repos.yml
    tags: clone_repos

  - name: Build Docker Images
    include: tasks/image_build.yml
    tags: images

  - name: Containers Pre-Provision
    include: tasks/container-preprovisioning.yml
    tags: [ containers, pre-prov ]

  - name: Install Containers
    include: tasks/containers.yml
    tags:  containers 

- name: "DNS"
  hosts: master_node
  vars_files:
    - vars/lists.yml
  become_user: "root"
  become: true
  tasks:
  - name: Post Provisioning DNS Tasks
    include: tasks/dns.yml
    tags: post
    
  - name: Cloudflare DNS 
    include: tasks/cloudflare.yml
    tags: cloudflare

- name: "POST PROVISIONING"
  hosts: all
  become_user: "root"
  become: true
  tasks:
  - name: Post Provisioning CRON Tasks
    include: tasks/cron.yml
    tags: 
     - post
     - cron
  - name: Update Actions
    include: tasks/update_ubuntu.yml
    tags: update_ubuntu
  - name: Reboot Actions
    include: tasks/reboot.yml
    tags: reboot

- name: "Backups"
  hosts: master_node
  become_user: "root"
  become: true
  tasks:
  - name: Backup Tasks
    include: tasks/backups.yml
    tags: backups