# PRE-provisioning VM
- name: "Provision Enviorment"
  strategy: linear
  hosts: all
  become: true 
  tasks:
  
  - name: Debiug VARS
    include_tasks: 
      file: tasks/debug.yml
      apply:
        tags: always
    tags: always
  
  - name: Install Required Packages
    include_tasks: 
      file: tasks/provisioning.yml
      apply:
        tags: packages
    tags: packages
  - name: Setup SSH
    include_tasks: 
      file: tasks/ssh_setup.yml
      apply:
        tags: ssh
    tags: ssh
  - name: Setup firewall
    include_tasks: 
      file: tasks/ufw.yml
      apply:
        tags: ufw
    tags: ufw

# Swarm setup
- name: "Configure Swarm"
  hosts: master_node
  become_user: "root"
  become: true
  tasks:
  - name: Install swarm
    include_tasks: 
      file: tasks/swarm_master.yml
      apply:
        tags: swarm
    tags: swarm

- name: "Join Swarm"
  hosts: 
    - worker_node_1
    - worker_node_2
  become_user: "root"
  become: true
  tasks:
  - name: Install swarm
    include_tasks: 
      file: tasks/swarm_worker_join.yml
      apply:
        tags: swarm
    tags: swarm

# Containers
- name: "Launch Swarm Containers"
  hosts: master_node
  become_user: "root"
  become: true
  vars_files:
    - vars/lists.yml
  tasks:
  - name: Git Clone App Repos
    include_tasks: 
      file: tasks/clone_app_repos.yml
      apply:
        tags: clone_repos 
    tags: clone_repos

  - name: Build Docker Images
    include_tasks: 
      file: tasks/image_build.yml
      apply:
       tags: images
    tags: images

  - name: Containers Pre-Provision
    include_tasks: 
      file: tasks/container-preprovisioning.yml
      apply:
        tags: [containers, pre-prov]
    tags: [containers, pre-prov]

  - name: Install Containers
    include_tasks: 
      file: tasks/containers.yml
      apply:
       tags: containers
    tags:  containers 

- name: "DNS"
  hosts: master_node
  vars_files:
    - vars/lists.yml
  become_user: "root"
  become: true
  tasks:
  - name: Post Provisioning DNS Tasks
    include_tasks: 
      file: tasks/dns.yml
      apply:
        tags: post
    tags: post
    
  - name: Cloudflare DNS 
    include_tasks: 
      file: tasks/cloudflare.yml
      apply:
        tags: cloudflare
    tags: cloudflare

- name: "POST PROVISIONING"
  hosts: all
  become_user: "root"
  become: true
  tasks:
  - name: Post Provisioning CRON Tasks
    include_tasks: 
      file: tasks/cron.yml
      apply:
        tags: [post, cron]
    tags: [post, cron]

  - name: Update Actions
    include_tasks: 
      file: tasks/update_ubuntu.yml
      apply:
        tags: update_ubuntu
    tags: update_ubuntu
  - name: Reboot Actions
    include_tasks: 
      file: tasks/reboot.yml
      apply:
        tags: reboot
    tags: reboot

- name: "Backups"
  hosts: master_node
  become_user: "root"
  become: true
  tasks:
  - name: Backup Tasks
    include_tasks:
      file: tasks/backups.yml
      apply:
        tags: backups
    tags: backups