# for testing only
---
services:
  ez-backups-glusterfs:
    image: jtmb92/ez-backups:latest
    environment:
      scheduled_hour: '19'
      scheduled_minute: '16'
      WEBHOOK_URL: "${discord_webhook}"
      local_backup_method: tar
      source_dir: '${container_volumes_location}'
      backup_destination: /mnt/backups/server-backups/container_volumes_location
      TZ: America/New_York
    volumes:
      - ${container_volumes_location}:${container_volumes_location}
      - /mnt/backups/server-backups/container_volumes_location:/mnt/backups/server-backups/container_volumes_location
    deploy:
        replicas: 1
        placement:
            max_replicas_per_node: 1
    logging:
        driver: loki
        options:
            loki-url: "http://localhost:3100/loki/api/v1/push"
            loki-retries: "5"
            loki-batch-size: "400"

  ez-backups-nfs:
    image: jtmb92/ez-backups:latest
    environment:
      scheduled_hour: '20'
      scheduled_minute: '16'
      WEBHOOK_URL: "${discord_webhook}"
      local_backup_method: tar
      source_dir: '${nfs_volumes_location}'
      backup_destination: /mnt/backups/server-backups/nfs_volumes_location
      TZ: America/New_York
    volumes:
      - ${nfs_volumes_location}:${nfs_volumes_location}
      - /mnt/backups/server-backups/nfs_volumes_location:/mnt/backups/server-backups/nfs_volumes_location
    deploy:
        replicas: 1
        placement:
            max_replicas_per_node: 1
    logging:
        driver: loki
        options:
            loki-url: "http://localhost:3100/loki/api/v1/push"
            loki-retries: "5"
            loki-batch-size: "400"

  ez-backups-plex:
    image: jtmb92/ez-backups:latest
    environment:
      scheduled_hour: '21'
      scheduled_minute: '16'
      WEBHOOK_URL: "${discord_webhook}"
      local_backup_method: tar
      source_dir: '/var/plex-stack/plex/config'
      backup_destination: /mnt/backups/server-backups/plex
      TZ: America/New_York
    volumes:
      - /var/plex-stack/plex/config:/var/plex-stack/plex/config
      - /mnt/backups/server-backups/plex:/mnt/backups/server-backups/plex
    deploy:
      placement:
        constraints:
          - node.hostname == masternode
    logging:
        driver: loki
        options:
            loki-url: "http://localhost:3100/loki/api/v1/push"
            loki-retries: "5"
            loki-batch-size: "400"
networks:
    container-swarm-network:
     external: true