version: '3'

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    devices:
      - /dev/dri:/dev/dri
    ports:
     - 32400:32400
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=America/Toronto
      - ADVERTISE_IP=http://${master_node}:32400/,https://plex.tv.lan
    volumes:
      - ${container_volumes_location}/plex/config:/config
      - /mnt/plex_smb_share/tv:/tv
      - /mnt/plex_smb_share/movies:/movies
      - /mnt/plex_smb_share/extras:/extras      
      - /dev/shm:/transcode
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
networks:
 container-swarm-network:
    external: true