version: '3'

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 32400:32400
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=America/Toronto
      # - PLEX_CLAIM=claim-your-token-here #claim token at https://www.plex.tv/claim/ (used for when a password change is needed or server needs to be reclaimed)
      - ADVERTISE_IP=http://${master_node}:32400/,https://plex.tv.lan
    volumes:
      - ${container_volumes_location}/plex/config:/config
      - /mnt/plex_smb_share/tv:/tv
      - /mnt/plex_smb_share/movies:/movies
      - /mnt/plex_smb_share/extras:/extras
      - /dev/shm:/transcode

  maintainerr:
    image: ghcr.io/jorenn92/maintainerr:latest # or jorenn92/maintainerr:latest
    container_name: maintainerr
    user: 1000:1000
    volumes:
      - ${container_volumes_location}/maintainerr:/opt/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    #      - DEBUG=true # uncomment to enable debug logs
    ports:
      - 6246:6246
    restart: unless-stopped
networks:
  container-swarm-network:
    external: true
