version: '3'
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    ports:
      - 32400:32400
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=America/Toronto
      # - PLEX_CLAIM=claim-your-token-here #claim token at https://www.plex.tv/claim/ (used for when a password change is needed or server needs to be reclaimed)
      - ADVERTISE_IP=http://192.168.0.17:32400/,https://plex.tv.lan
    volumes:
      - /p/container-program-files/plex/config:/config
      - /mnt/plex_smb_share/tv:/tv
      - /mnt/plex_smb_share/movies:/movies
      - /mnt/plex_smb_share/extras:/extras