version: '3.8'

services:
  spiderfoot:
    image: josaorg/spiderfoot:stable
    container_name: spiderfoot
    ports:
      - "5001:5001"
    volumes:
      - ${container_volumes_location}/spiderfoot_data:/var/lib/spiderfoot
    restart: unless-stopped
    networks:
      - container-swarm-network
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.spiderfoot.rule=Host(`spiderfoot.${domain_name}`)"
        - "traefik.http.services.spiderfoot.loadbalancer.server.port=5001" #uses internal docker port
        - "traefik.http.routers.spiderfoot.entrypoints=websecure"
        - "traefik.http.routers.spiderfoot.tls=true"
        - "traefik.http.routers.spiderfoot.tls.certresolver=myresolver"
        - "traefik.http.routers.spiderfoot.tls.domains[0].main=spiderfoot.${domain_name}"
        # to add additional DNS names
        # - "traefik.http.routers.spiderfoot.tls.domains[0].sans=spiderfoot.${domain_name}"
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.hostname == masternode ]
networks:
  container-swarm-network:
    external: true
