version: '3.8'
services:
  lucinda:
    image: 'nginx'
    networks:
      - container-swarm-network
    restart: unless-stopped
    ports:
      - '8080:80'
    environment:
      DISABLE_IPV6: 'true'
    volumes:
      - ${container_volumes_location}/ws-lucinda:/usr/share/nginx/html
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-retries: "5"
        loki-batch-size: "400"

  santos:
    image: 'nginx'
    networks:
      - container-swarm-network
    restart: unless-stopped
    ports:
      - '8081:80'
    environment:
      DISABLE_IPV6: 'true'
    volumes:
      - ${container_volumes_location}/ws-santos:/usr/share/nginx/html
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-retries: "5"
        loki-batch-size: "400"

  aplb:
    image: 'nginx'
    networks:
      - container-swarm-network
    restart: unless-stopped
    ports:
      - '8082:80'
    environment:
      DISABLE_IPV6: 'true'
    volumes:
      - ${container_volumes_location}/ws-aplb:/usr/share/nginx/html
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-retries: "5"
        loki-batch-size: "400"

  mcwebsite:
    image: 'nginx'
    networks:
      - container-swarm-network
    restart: unless-stopped
    ports:
      - '8083:80'
    environment:
      DISABLE_IPV6: 'true'
    volumes:
      - ${container_volumes_location}/mc-branconet-lan:/usr/share/nginx/html
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-retries: "5"
        loki-batch-size: "400"

networks:
 container-swarm-network:
    external: true