version: '3.8'
services:
  lucinda:
    image: 'nginx'
    networks:
      - container-swarm-network
    restart: unless-stopped
    ports:
      - '8080:80'
    environment:
      DISABLE_IPV6: 'true'
    volumes:
      - /home/ubuntu/container-program-files/ws-lucinda:/usr/share/nginx/html

  santos:
    image: 'nginx'
    networks:
      - container-swarm-network
    restart: unless-stopped
    ports:
      - '8081:80'
    environment:
      DISABLE_IPV6: 'true'
    volumes:
      - /home/ubuntu/container-program-files/ws-santos:/usr/share/nginx/html

  aplb:
    image: 'nginx'
    networks:
      - container-swarm-network
    restart: unless-stopped
    ports:
      - '8082:80'
    environment:
      DISABLE_IPV6: 'true'
    volumes:
      - /home/ubuntu/container-program-files/ws-aplb:/usr/share/nginx/html
networks:
 container-swarm-network:
    external: true