services:

  prometheus:
    image: prom/prometheus
    user: "0"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9091:9090
    networks:
      - container-swarm-network
    restart: unless-stopped
    volumes:
      - '${container_volumes_location}/prometheus:/etc/prometheus'
      - '${container_volumes_location}/prometheus/prom_data:/prometheus'
    deploy:
      labels:
        #homepage
        - homepage.group=Monitoring
        - homepage.name=prometheus
        - homepage.icon=https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Prometheus_software_logo.svg/2066px-Prometheus_software_logo.svg.png
        - 'homepage.href=http://prometheus.${lan_domain_name}/'
        - homepage.description=prometheus logs
        #traefik
        - "traefik.enable=true"
        - "traefik.http.routers.prometheus.rule=Host(`prometheus.${lan_domain_name}`)"
        - "traefik.http.services.prometheus.loadbalancer.server.port=9090" #uses internal docker port
        - "traefik.http.routers.prometheus.entrypoints=websecure"
        - "traefik.http.routers.prometheus.tls=true"
        - "traefik.http.routers.prometheus.tls.certresolver=myresolver"
        - "traefik.http.routers.prometheus.tls.domains[0].main=prometheus.${lan_domain_name}"
      replicas: 1

  loki:
    user: "0"
    image: grafana/loki:2.3.0
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - container-swarm-network
    volumes:
      - '${container_volumes_location}/loki/config:/etc/loki'
      - '${container_volumes_location}/loki/data:/data/loki'
    deploy:
      labels:
        #homepage
        - homepage.group=Monitoring
        - homepage.name=loki
        - homepage.icon=https://upload.wikimedia.org/wikipedia/commons/0/07/Grafana_loki_logo.png
        - 'homepage.href=http://loki.${lan_domain_name}/'
        - homepage.description=loki logs
        #traefik
        - "traefik.enable=true"
        - "traefik.http.routers.loki.rule=Host(`loki.${lan_domain_name}`)"
        - "traefik.http.services.loki.loadbalancer.server.port=3100" #uses internal docker port
        - "traefik.http.routers.loki.entrypoints=websecure"
        - "traefik.http.routers.loki.tls=true"
        - "traefik.http.routers.loki.tls.certresolver=myresolver"
        - "traefik.http.routers.loki.tls.domains[0].main=loki.${lan_domain_name}"
        # to add additional DNS names
        # - "traefik.http.routers.loki.tls.domains[0].sans=loki.${lan_domain_name}"
      replicas: 1

  uptime-kuma:
    image: louislam/uptime-kuma:debian
    deploy:
      labels:
        #homepage
        - homepage.group=Monitoring
        - homepage.name=uptime-kuma
        - homepage.icon=https://static-00.iconduck.com/assets.00/uptime-kuma-icon-2048x1892-iigw6pmz.png
        - 'homepage.href=http://uptime.${lan_domain_name}/'
        - homepage.description=uptime monitoring
        #traefik
        - "traefik.enable=true"
        - "traefik.http.routers.uptime.rule=Host(`uptime.${lan_domain_name}`)"
        - "traefik.http.services.uptime.loadbalancer.server.port=3001" #uses internal docker port
        - "traefik.http.routers.uptime.entrypoints=websecure"
        - "traefik.http.routers.uptime.tls=true"
        - "traefik.http.routers.uptime.tls.certresolver=myresolver"
        - "traefik.http.routers.uptime.tls.domains[0].main=uptime.${lan_domain_name}"
        # to add additional DNS names
        # - "traefik.http.routers.uptime.tls.domains[0].sans=uptime.${lan_domain_name}"
    ports:
      - 3001:3001
    restart: unless-stopped
    networks:
      - container-swarm-network
    volumes:
      - '${container_volumes_location}/uptime-kuma:/app/data'

  node-exporter:
    image: flaviostutz/docker-swarm-node-exporter
    environment:
      - NODE_ID={{.Node.Hostname}}
      - HOSTNAME={{.Node.Hostname}}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    networks:
      - container-swarm-network
    ports:
      - 9100:9100
    deploy:
      labels:
        #homepage
        - homepage.group=Monitoring
        - homepage.name=node-exporter
        - homepage.icon=https://www.stackhero.io/assets/src/images/servicesLogos/openGraphVersions/prometheus.png?552669da
        - 'homepage.href=http://node.${lan_domain_name}/'
        - homepage.description=node exporter
        #traefik
        - "traefik.enable=true"
        - "traefik.http.routers.node.rule=Host(`node.${lan_domain_name}`)"
        - "traefik.http.services.node.loadbalancer.server.port=9100" #uses internal docker port
        - "traefik.http.routers.node.entrypoints=websecure"
        - "traefik.http.routers.node.tls=true"
        - "traefik.http.routers.node.tls.certresolver=myresolver"
        - "traefik.http.routers.node.tls.domains[0].main=node.${lan_domain_name}"
        # to add additional DNS names
        # - "traefik.http.routers.node.tls.domains[0].sans=node.${lan_domain_name}"
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  grafana:
    image: grafana/grafana
    deploy:
      labels:
        #homepage
        - homepage.group=Monitoring
        - homepage.name=grafana
        - homepage.icon=https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Grafana_logo.svg/1200px-Grafana_logo.svg.png
        - 'homepage.href=http://grafana.${lan_domain_name}/'
        - homepage.description=Grafana timeseries dashboards
        #traefik
        - "traefik.enable=true"
        - "traefik.http.routers.grafana.rule=Host(`grafana.${lan_domain_name}`)"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000" #uses internal docker port
        - "traefik.http.routers.grafana.entrypoints=websecure"
        - "traefik.http.routers.grafana.tls=true"
        - "traefik.http.routers.grafana.tls.certresolver=myresolver"
        - "traefik.http.routers.grafana.tls.domains[0].main=grafana.${lan_domain_name}"
        # to add additional DNS names
        # - "traefik.http.routers.grafana.tls.domains[0].sans=grafana.${lan_domain_name}"
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - container-swarm-network
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: ${ADMIN_PASS}
      GF_INSTALL_PLUGINS: grafana-piechart-panel
    user: "0"
    volumes:
      - '${container_volumes_location}/grafana/datasources:/etc/grafana/provisioning/datasources'
      - '${container_volumes_location}/grafana/data:/var/lib/grafana'
networks:
  container-swarm-network:
    external: true
