---
version: "3.8"
services:
  bookstack-app-wan:
    image: lscr.io/linuxserver/bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://bookstack.jtmb.cc
      - DB_HOST=bookstack-db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=${ADMIN_PASS}
      - DB_DATABASE=bookstackapp
    volumes:
      - ${container_volumes_location}/bookstack/bookstack_app_data:/config
    ports:
      - 6875:80
    depends_on:
      - bookstack-db
    restart: unless-stopped
    networks:
     - container-swarm-network
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1

  bookstack-app-lan:
    image: lscr.io/linuxserver/bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://bookstack.branconet.lan
      - DB_HOST=bookstack-db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=${ADMIN_PASS}
      - DB_DATABASE=bookstackapp
    volumes:
      - ${container_volumes_location}/bookstack/bookstack_app_data:/config
    ports:
      - 6876:80
    depends_on:
      - bookstack-db
    restart: unless-stopped
    networks:
     - container-swarm-network
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1


  bookstack-db:
    image: lscr.io/linuxserver/mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${ADMIN_PASS}
      - TZ=Europe/London
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=${ADMIN_PASS}
    volumes:
      - ${container_volumes_location}/bookstack/bookstack_db_data:/config
    restart: unless-stopped
    networks:
     - container-swarm-network
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
networks:
    container-swarm-network:
     external: true