apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./plex
  - ./radarr
  - ./overseerr
  - ./bazarr
  - ./sonarr
  - ./ytdl
  - ./jackett
  - ./unpackerr
  - ./flaresolverr
  - ./tautulli
  - ./qbittorrent
  - ./qbit-monitor
