version: '3'

services:
  vaultwarden:
    image: dperson/openvpn-client
    restart: always
    cap_add:
      - NET_ADMIN
    environment:
      SIGNUPS_ALLOWED: "true"
      PUID: 1000 
      PGID: 1000
      DATABASE_URL: mysql://bitwarden:${ADMIN_PASS}@mariadb:/bitwarden
    volumes:
      - /home/ubuntu/container-program-files/vault_warden/swarm:/data
    ports:
      - 8096:80
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 2
        # constraints:
        # - node.role==worker